services:
  - type: web
    name: plants-app
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/plants.dll
    plan: free
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CONNECTION_STRINGS__DEFAULTCONNECTION
        value: "Server=<your_server>;Database=<your_database>;User Id=<your_user>;Password=<your_password>;"
