services:
  - type: web
    name: plants-app
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/plants.dll
    plan: free
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CONNECTION_STRINGS__DEFAULTCONNECTION
        value: "Server=DESKTOP-39EDKOS,1433;Database=FlowerShop;User Id=natsy;Password=root;"
